// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsHome.IL.Repository.EF;

#nullable disable

namespace SportsHome.IL.Repository.EF.Migrations
{
    [DbContext(typeof(SportsHomeContext))]
    [Migration("20260329121834_Crear_tabla_EstadisticasJugadores")]
    partial class Crear_tabla_EstadisticasJugadores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SportsHome.Core.Entities.Equipos", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EquipoId"));

                    b.Property<int?>("CapacidadEstadio")
                        .HasColumnType("int");

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<int?>("Fundacion")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreEstadio")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("EquipoId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.EstadisticasEquiposPartidos", b =>
                {
                    b.Property<int>("EstadisticaPartidoEquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EstadisticaPartidoEquipoId"));

                    b.Property<int?>("Corners")
                        .HasColumnType("int");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int?>("Faltas")
                        .HasColumnType("int");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Posesion")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("TarjetasAmarillas")
                        .HasColumnType("int");

                    b.Property<int?>("TarjetasRojas")
                        .HasColumnType("int");

                    b.Property<int?>("TirosAPuerta")
                        .HasColumnType("int");

                    b.Property<int?>("TirosFuera")
                        .HasColumnType("int");

                    b.HasKey("EstadisticaPartidoEquipoId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("PartidoId", "EquipoId")
                        .IsUnique();

                    b.ToTable("EstadisticasEquiposPartidos");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.EstadisticasJugadores", b =>
                {
                    b.Property<int>("EstadisticaJugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EstadisticaJugadorId"));

                    b.Property<int?>("Apariciones")
                        .HasColumnType("int");

                    b.Property<int?>("Asistencias")
                        .HasColumnType("int");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int?>("Goles")
                        .HasColumnType("int");

                    b.Property<int>("JugadorId")
                        .HasColumnType("int");

                    b.Property<int>("LigaId")
                        .HasColumnType("int");

                    b.Property<int?>("Minutos")
                        .HasColumnType("int");

                    b.Property<int?>("TarjetasAmarillas")
                        .HasColumnType("int");

                    b.Property<int?>("TarjetasRojas")
                        .HasColumnType("int");

                    b.Property<int>("Temporada")
                        .HasColumnType("int");

                    b.HasKey("EstadisticaJugadorId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("LigaId");

                    b.HasIndex("JugadorId", "EquipoId", "LigaId", "Temporada")
                        .IsUnique();

                    b.ToTable("EstadisticasJugadores");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.EventosPartidos", b =>
                {
                    b.Property<int>("EventoPartidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EventoPartidoId"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int?>("JugadorId")
                        .HasColumnType("int");

                    b.Property<int>("Minuto")
                        .HasColumnType("int");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("EventoPartidoId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("JugadorId");

                    b.HasIndex("PartidoId");

                    b.HasIndex("PartidoId", "Minuto");

                    b.ToTable("EventosPartidos");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.Jugadores", b =>
                {
                    b.Property<int>("JugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("JugadorId"));

                    b.Property<string>("Altura")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NombrePropio")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Peso")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("JugadorId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.JugadoresEquipos", b =>
                {
                    b.Property<int>("JugadorEquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("JugadorEquipoId"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("JugadorId")
                        .HasColumnType("int");

                    b.Property<int>("Temporada")
                        .HasColumnType("int");

                    b.HasKey("JugadorEquipoId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("JugadorId", "EquipoId", "Temporada")
                        .IsUnique();

                    b.ToTable("JugadoresEquipos");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.Ligas", b =>
                {
                    b.Property<int>("LigaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LigaId"));

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("LigaId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Ligas");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.LigasTemporadas", b =>
                {
                    b.Property<int>("LigaTemporadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LigaTemporadaId"));

                    b.Property<int>("LigaId")
                        .HasColumnType("int");

                    b.Property<int>("Temporada")
                        .HasColumnType("int");

                    b.HasKey("LigaTemporadaId");

                    b.HasIndex("LigaId", "Temporada")
                        .IsUnique();

                    b.ToTable("LigasTemporadas");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.Partidos", b =>
                {
                    b.Property<int>("PartidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PartidoId"));

                    b.Property<string>("Arbitro")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("EquipoLocalId")
                        .HasColumnType("int");

                    b.Property<int>("EquipoVisitanteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GolesLocal")
                        .HasColumnType("int");

                    b.Property<int?>("GolesVisitante")
                        .HasColumnType("int");

                    b.Property<int>("LigaId")
                        .HasColumnType("int");

                    b.Property<string>("Ronda")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Temporada")
                        .HasColumnType("int");

                    b.Property<string>("ZonaHoraria")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PartidoId");

                    b.HasIndex("EquipoLocalId");

                    b.HasIndex("EquipoVisitanteId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("LigaId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.EstadisticasEquiposPartidos", b =>
                {
                    b.HasOne("SportsHome.Core.Entities.Equipos", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsHome.Core.Entities.Partidos", "Partido")
                        .WithMany("Estadisticas")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.EstadisticasJugadores", b =>
                {
                    b.HasOne("SportsHome.Core.Entities.Equipos", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsHome.Core.Entities.Jugadores", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsHome.Core.Entities.Ligas", "Liga")
                        .WithMany()
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Jugador");

                    b.Navigation("Liga");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.EventosPartidos", b =>
                {
                    b.HasOne("SportsHome.Core.Entities.Equipos", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsHome.Core.Entities.Jugadores", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportsHome.Core.Entities.Partidos", "Partido")
                        .WithMany("Eventos")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Jugador");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.JugadoresEquipos", b =>
                {
                    b.HasOne("SportsHome.Core.Entities.Equipos", "Equipo")
                        .WithMany("JugadoresEquipos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsHome.Core.Entities.Jugadores", "Jugador")
                        .WithMany("JugadoresEquipos")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.LigasTemporadas", b =>
                {
                    b.HasOne("SportsHome.Core.Entities.Ligas", "Liga")
                        .WithMany("Temporadas")
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liga");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.Partidos", b =>
                {
                    b.HasOne("SportsHome.Core.Entities.Equipos", "EquipoLocal")
                        .WithMany("PartidosLocal")
                        .HasForeignKey("EquipoLocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsHome.Core.Entities.Equipos", "EquipoVisitante")
                        .WithMany("PartidosVisitante")
                        .HasForeignKey("EquipoVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SportsHome.Core.Entities.Ligas", "Liga")
                        .WithMany("Partidos")
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");

                    b.Navigation("Liga");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.Equipos", b =>
                {
                    b.Navigation("JugadoresEquipos");

                    b.Navigation("PartidosLocal");

                    b.Navigation("PartidosVisitante");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.Jugadores", b =>
                {
                    b.Navigation("JugadoresEquipos");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.Ligas", b =>
                {
                    b.Navigation("Partidos");

                    b.Navigation("Temporadas");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.Partidos", b =>
                {
                    b.Navigation("Estadisticas");

                    b.Navigation("Eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
