// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsHome.IL.Repository.EF;

#nullable disable

namespace SportsHome.IL.Repository.EF.Migrations
{
    [DbContext(typeof(SportsHomeContext))]
    [Migration("20260328134610_Crear_tabla_Jugadores_Real")]
    partial class Crear_tabla_Jugadores_Real
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SportsHome.Core.Entities.Equipos", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EquipoId"));

                    b.Property<int?>("CapacidadEstadio")
                        .HasColumnType("int");

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<int?>("Fundacion")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreEstadio")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("EquipoId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.Jugadores", b =>
                {
                    b.Property<int>("JugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("JugadorId"));

                    b.Property<string>("Altura")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NombrePropio")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Peso")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("JugadorId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.Ligas", b =>
                {
                    b.Property<int>("LigaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LigaId"));

                    b.Property<int>("ExternalId")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("LigaId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Ligas");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.LigasTemporadas", b =>
                {
                    b.Property<int>("LigaTemporadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LigaTemporadaId"));

                    b.Property<int>("LigaId")
                        .HasColumnType("int");

                    b.Property<int>("Temporada")
                        .HasColumnType("int");

                    b.HasKey("LigaTemporadaId");

                    b.HasIndex("LigaId", "Temporada")
                        .IsUnique();

                    b.ToTable("LigasTemporadas");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.LigasTemporadas", b =>
                {
                    b.HasOne("SportsHome.Core.Entities.Ligas", "Liga")
                        .WithMany("Temporadas")
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liga");
                });

            modelBuilder.Entity("SportsHome.Core.Entities.Ligas", b =>
                {
                    b.Navigation("Temporadas");
                });
#pragma warning restore 612, 618
        }
    }
}
